FROM node:18 as builder

# WORKDIR in docker container
WORKDIR /frontend

# Docker uses caching so install all the dependencies first
COPY package.json .
RUN npm install

# Source code changes much more often so easier to rebuild the image when you structure like this
# copy react app to the container
COPY . .

RUN npm run build

# prepare nginx
FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /frontend/build /usr/share/nginx/html