version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - /frontend/node_modules
      - ./frontend/src:/frontend/src
    env_file:
      - ./.env
    environment:
      - WDS_SOCKET_PORT=0 # Fixes bug where websocket connection is fixed to default port 3000
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env
    environment:
      POSTGRES_URI: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    depends_on:
      - postgres
  nginx:
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
    ports:
      - 8080:80
  postgres:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    name: postgres-data
    # driver: local # default driver is local
