version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - /frontend/node_modules
      - ./frontend/src:/frontend/src
    environment:
      - WDS_SOCKET_PORT=0 # Fixes bug where websocket connection is fixed to default port 3000
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    environment:
      POSTGRES_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5001:5001
  nginx:
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
    ports:
      - 8080:80
  postgres:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:
    # driver: local # default driver is local
